LAMBDA_WARNING: Unhandled exception. The most likely cause is an issue in the function code. However, in rare cases, a Lambda runtime update can cause unexpected function behavior. For functions using managed runtimes, runtime updates can be triggered by a function change, or can be applied automatically. To determine if the runtime has been updated, check the runtime version in the INIT_START log entry. If this error correlates with a change in the runtime version, you may be able to mitigate this error by temporarily rolling back to the previous runtime version. For more information, see https://docs.aws.amazon.com/lambda/latest/dg/runtimes-update.html

[ERROR] KeyError: 'httpMethod'
Traceback (most recent call last):
  File "/var/task/lambda_function.py", line 40, in lambda_handler
    return app.resolve(event, context)
  File "/opt/python/lib/python3.9/site-packages/aws_lambda_powertools/event_handler/api_gateway.py", line 1918, in resolve
    response = self._resolve().build(self.current_event, self._cors)
  File "/opt/python/lib/python3.9/site-packages/aws_lambda_powertools/event_handler/api_gateway.py", line 2012, in _resolve
    method = self.current_event.http_method.upper()
  File "/opt/python/lib/python3.9/site-packages/aws_lambda_powertools/utilities/data_classes/common.py", line 173, in http_method
    return self["httpMethod"]
  File "/opt/python/lib/python3.9/site-packages/aws_lambda_powertools/utilities/data_classes/common.py", line 32, in __getitem__
    return self._data[key]
