{"errorMessage": "'Router' object has no attribute 'resolve'", "errorType": "AttributeError", "requestId": "a1c7ce9d-be3b-46e8-ba74-1804e398d97c", "stackTrace": ["  File \"/var/task/lambda_function.py\", line 45, in lambda_handler\n    return router.resolve(event, context)\n"]}
